#include <tchar.h>
#include <random>
#pragma comment(lib, "urlmon.lib")
#include <urlmon.h>
#include <sstream>
#include <iostream>
#include <Lmcons.h>
#include <string>
#include <random>
#include <Windows.h>
#include "Main.h"
#include <Windows.h>
#include <string>
#include <cstdlib>
#include <stdlib.h>
#include <ostream>
#include <random>
#include <tchar.h>
#include <regex>
#include <sstream>
#include <winbase.h>
#include <time.h>
#include <stdio.h>
#include <WinInet.h>
#include <filesystem>
#include <fstream>
#include <string.h>
#include <cstring>
#include <ctime>
#include <ctime>
#include <string.h>
#include <string>
#include <stdio.h> 
#include <fstream>
#include <chrono>
#include "mix/xor.h"
#include "mix/md5.h"
#pragma comment(lib, "user32.lib")
